version: '3'
services:
  mchahnapi:
    image: mchahnapi #image name, Default:- Folder Name
    build:
      context: ./mcHahnAPI/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  mchahnfrontapp:
    image: mchahnfrontapp #image name, Default: - Folder Name
    build:
      context: ./mcHannFrontApp/
      dockerfile: Dockerfile
    ports:
      - "80:80"
